# Generated by Django 4.2.3 on 2023-07-07 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='image',
            field=models.ImageField(default='hrhh', upload_to='gallery'),
            preserve_default=False,
        ),
    ]
